// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"context"
	"fmt"
	"net/url"
	"time"

	"github.com/gofiber/fiber/v3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConversationOpenStatus.
const (
	ConversationOpenStatusNoOpenDetected ConversationOpenStatus = "no_open_detected"
	ConversationOpenStatusOpenDetected   ConversationOpenStatus = "open_detected"
)

// Valid indicates whether the value is a known member of the ConversationOpenStatus enum.
func (e ConversationOpenStatus) Valid() bool {
	switch e {
	case ConversationOpenStatusNoOpenDetected:
		return true
	case ConversationOpenStatusOpenDetected:
		return true
	default:
		return false
	}
}

// Defines values for ConversationDetailOpenStatus.
const (
	ConversationDetailOpenStatusNoOpenDetected ConversationDetailOpenStatus = "no_open_detected"
	ConversationDetailOpenStatusOpenDetected   ConversationDetailOpenStatus = "open_detected"
)

// Valid indicates whether the value is a known member of the ConversationDetailOpenStatus enum.
func (e ConversationDetailOpenStatus) Valid() bool {
	switch e {
	case ConversationDetailOpenStatusNoOpenDetected:
		return true
	case ConversationDetailOpenStatusOpenDetected:
		return true
	default:
		return false
	}
}

// Defines values for DeliveryStatus.
const (
	Failed   DeliveryStatus = "failed"
	Pending  DeliveryStatus = "pending"
	Prepared DeliveryStatus = "prepared"
	Sent     DeliveryStatus = "sent"
	Unknown  DeliveryStatus = "unknown"
)

// Valid indicates whether the value is a known member of the DeliveryStatus enum.
func (e DeliveryStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Prepared:
		return true
	case Sent:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for SendInputSendMode.
const (
	Separate SendInputSendMode = "separate"
	Shared   SendInputSendMode = "shared"
)

// Valid indicates whether the value is a known member of the SendInputSendMode enum.
func (e SendInputSendMode) Valid() bool {
	switch e {
	case Separate:
		return true
	case Shared:
		return true
	default:
		return false
	}
}

// AddonPairInput defines model for AddonPairInput.
type AddonPairInput struct {
	Code          string `json:"code"`
	IdentityToken string `json:"identityToken"`
}

// AddonPairResult defines model for AddonPairResult.
type AddonPairResult struct {
	MailboxId string `json:"mailboxId"`
}

// AddonPrepareInput defines model for AddonPrepareInput.
type AddonPrepareInput struct {
	IdentityToken string   `json:"identityToken"`
	Recipients    []string `json:"recipients"`
	Subject       string   `json:"subject"`
}

// AddonPrepareResult defines model for AddonPrepareResult.
type AddonPrepareResult struct {
	ConversationId string `json:"conversationId"`
	PixelUrl       string `json:"pixelUrl"`
}

// ConnectURL defines model for ConnectURL.
type ConnectURL struct {
	Url string `json:"url"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	Id         string                 `json:"id"`
	MailboxId  string                 `json:"mailboxId"`
	OpenStatus ConversationOpenStatus `json:"openStatus"`
	Status     string                 `json:"status"`
	Subject    string                 `json:"subject"`
	UpdatedAt  time.Time              `json:"updatedAt"`
}

// ConversationOpenStatus defines model for Conversation.OpenStatus.
type ConversationOpenStatus string

// ConversationDetail defines model for ConversationDetail.
type ConversationDetail struct {
	Deliveries []Delivery                   `json:"deliveries"`
	Events     []OpenEvent                  `json:"events"`
	Id         string                       `json:"id"`
	MailboxId  string                       `json:"mailboxId"`
	OpenStatus ConversationDetailOpenStatus `json:"openStatus"`
	Status     string                       `json:"status"`
	Subject    string                       `json:"subject"`
	UpdatedAt  time.Time                    `json:"updatedAt"`
}

// ConversationDetailOpenStatus defines model for ConversationDetail.OpenStatus.
type ConversationDetailOpenStatus string

// Delivery defines model for Delivery.
type Delivery struct {
	Error          *string        `json:"error,omitempty"`
	GmailMessageId *string        `json:"gmailMessageId,omitempty"`
	GmailThreadId  *string        `json:"gmailThreadId,omitempty"`
	Id             string         `json:"id"`
	Recipients     []string       `json:"recipients"`
	RfcMessageId   *string        `json:"rfcMessageId,omitempty"`
	Status         DeliveryStatus `json:"status"`
}

// DeliveryStatus defines model for Delivery.Status.
type DeliveryStatus string

// Draft defines model for Draft.
type Draft struct {
	Attachments      *[]string `json:"attachments,omitempty"`
	Bcc              []string  `json:"bcc"`
	Cc               []string  `json:"cc"`
	Html             string    `json:"html"`
	Id               string    `json:"id"`
	MailboxId        string    `json:"mailboxId"`
	ReplyToMessageId *string   `json:"replyToMessageId,omitempty"`
	Subject          string    `json:"subject"`
	ThreadId         *string   `json:"threadId,omitempty"`
	To               []string  `json:"to"`
	UpdatedAt        time.Time `json:"updatedAt"`
}

// DraftInput defines model for DraftInput.
type DraftInput struct {
	Attachments      *[]string `json:"attachments,omitempty"`
	Bcc              []string  `json:"bcc"`
	Cc               []string  `json:"cc"`
	Html             string    `json:"html"`
	Id               *string   `json:"id,omitempty"`
	MailboxId        string    `json:"mailboxId"`
	ReplyToMessageId *string   `json:"replyToMessageId,omitempty"`
	Subject          string    `json:"subject"`
	ThreadId         *string   `json:"threadId,omitempty"`
	To               []string  `json:"to"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// Mailbox defines model for Mailbox.
type Mailbox struct {
	ConnectedAt time.Time `json:"connectedAt"`
	Email       string    `json:"email"`
	Id          string    `json:"id"`
}

// OpenEvent defines model for OpenEvent.
type OpenEvent struct {
	At         time.Time `json:"at"`
	DeliveryId string    `json:"deliveryId"`
}

// PairingCode defines model for PairingCode.
type PairingCode struct {
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// PairingCodeInput defines model for PairingCodeInput.
type PairingCodeInput struct {
	MailboxId string `json:"mailboxId"`
}

// SendInput defines model for SendInput.
type SendInput struct {
	Draft          DraftInput        `json:"draft"`
	IdempotencyKey string            `json:"idempotencyKey"`
	SendMode       SendInputSendMode `json:"sendMode"`
}

// SendInputSendMode defines model for SendInput.SendMode.
type SendInputSendMode string

// SendResult defines model for SendResult.
type SendResult struct {
	ConversationId string     `json:"conversationId"`
	Deliveries     []Delivery `json:"deliveries"`
}

// ListConversationsParams defines parameters for ListConversations.
type ListConversationsParams struct {
	MailboxId *string `form:"mailboxId,omitempty" json:"mailboxId,omitempty"`
}

// PairAddonJSONRequestBody defines body for PairAddon for application/json ContentType.
type PairAddonJSONRequestBody = AddonPairInput

// PrepareAddonDraftJSONRequestBody defines body for PrepareAddonDraft for application/json ContentType.
type PrepareAddonDraftJSONRequestBody = AddonPrepareInput

// SaveDraftJSONRequestBody defines body for SaveDraft for application/json ContentType.
type SaveDraftJSONRequestBody = DraftInput

// CreatePairingCodeJSONRequestBody defines body for CreatePairingCode for application/json ContentType.
type CreatePairingCodeJSONRequestBody = PairingCodeInput

// SendTrackedMessageJSONRequestBody defines body for SendTrackedMessage for application/json ContentType.
type SendTrackedMessageJSONRequestBody = SendInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /addon/pair)
	PairAddon(c fiber.Ctx) error

	// (POST /addon/prepare)
	PrepareAddonDraft(c fiber.Ctx) error

	// (GET /conversations)
	ListConversations(c fiber.Ctx, params ListConversationsParams) error

	// (GET /conversations/{conversationId})
	GetConversation(c fiber.Ctx, conversationId string) error

	// (GET /drafts)
	ListDrafts(c fiber.Ctx) error

	// (POST /drafts)
	SaveDraft(c fiber.Ctx) error

	// (DELETE /drafts/{draftId})
	DeleteDraft(c fiber.Ctx, draftId string) error

	// (GET /drafts/{draftId})
	GetDraft(c fiber.Ctx, draftId string) error

	// (GET /health)
	GetHealth(c fiber.Ctx) error

	// (GET /mailboxes)
	ListMailboxes(c fiber.Ctx) error

	// (POST /mailboxes/connect)
	StartMailboxConnect(c fiber.Ctx) error

	// (DELETE /mailboxes/{mailboxId})
	RemoveMailbox(c fiber.Ctx, mailboxId string) error

	// (POST /pairing-codes)
	CreatePairingCode(c fiber.Ctx) error

	// (POST /send)
	SendTrackedMessage(c fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c fiber.Ctx, next fiber.Handler) error

// PairAddon operation middleware
func (siw *ServerInterfaceWrapper) PairAddon(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.PairAddon(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// PrepareAddonDraft operation middleware
func (siw *ServerInterfaceWrapper) PrepareAddonDraft(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.PrepareAddonDraft(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ListConversations operation middleware
func (siw *ServerInterfaceWrapper) ListConversations(c fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListConversationsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "mailboxId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "mailboxId", query, &params.MailboxId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter mailboxId: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.ListConversations(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetConversation operation middleware
func (siw *ServerInterfaceWrapper) GetConversation(c fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId string

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", c.Params("conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter conversationId: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.GetConversation(c, conversationId)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ListDrafts operation middleware
func (siw *ServerInterfaceWrapper) ListDrafts(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.ListDrafts(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// SaveDraft operation middleware
func (siw *ServerInterfaceWrapper) SaveDraft(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.SaveDraft(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// DeleteDraft operation middleware
func (siw *ServerInterfaceWrapper) DeleteDraft(c fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "draftId" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draftId", c.Params("draftId"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter draftId: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.DeleteDraft(c, draftId)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetDraft operation middleware
func (siw *ServerInterfaceWrapper) GetDraft(c fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "draftId" -------------
	var draftId string

	err = runtime.BindStyledParameterWithOptions("simple", "draftId", c.Params("draftId"), &draftId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter draftId: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.GetDraft(c, draftId)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.GetHealth(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ListMailboxes operation middleware
func (siw *ServerInterfaceWrapper) ListMailboxes(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.ListMailboxes(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// StartMailboxConnect operation middleware
func (siw *ServerInterfaceWrapper) StartMailboxConnect(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.StartMailboxConnect(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// RemoveMailbox operation middleware
func (siw *ServerInterfaceWrapper) RemoveMailbox(c fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "mailboxId" -------------
	var mailboxId string

	err = runtime.BindStyledParameterWithOptions("simple", "mailboxId", c.Params("mailboxId"), &mailboxId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter mailboxId: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.RemoveMailbox(c, mailboxId)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// CreatePairingCode operation middleware
func (siw *ServerInterfaceWrapper) CreatePairingCode(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.CreatePairingCode(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// SendTrackedMessage operation middleware
func (siw *ServerInterfaceWrapper) SendTrackedMessage(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.SendTrackedMessage(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/health", wrapper.GetHealth)

	router.Get(options.BaseURL+"/mailboxes", wrapper.ListMailboxes)

	router.Post(options.BaseURL+"/mailboxes/connect", wrapper.StartMailboxConnect)

	router.Delete(options.BaseURL+"/mailboxes/:mailboxId", wrapper.RemoveMailbox)

	router.Get(options.BaseURL+"/drafts", wrapper.ListDrafts)

	router.Post(options.BaseURL+"/drafts", wrapper.SaveDraft)

	router.Delete(options.BaseURL+"/drafts/:draftId", wrapper.DeleteDraft)

	router.Get(options.BaseURL+"/drafts/:draftId", wrapper.GetDraft)

	router.Post(options.BaseURL+"/send", wrapper.SendTrackedMessage)

	router.Get(options.BaseURL+"/conversations", wrapper.ListConversations)

	router.Get(options.BaseURL+"/conversations/:conversationId", wrapper.GetConversation)

	router.Post(options.BaseURL+"/pairing-codes", wrapper.CreatePairingCode)

	router.Post(options.BaseURL+"/addon/pair", wrapper.PairAddon)

	router.Post(options.BaseURL+"/addon/prepare", wrapper.PrepareAddonDraft)

}

type PairAddonRequestObject struct {
	Body *PairAddonJSONRequestBody
}

type PairAddonResponseObject interface {
	VisitPairAddonResponse(ctx fiber.Ctx) error
}

type PairAddon200JSONResponse AddonPairResult

func (response PairAddon200JSONResponse) VisitPairAddonResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type PrepareAddonDraftRequestObject struct {
	Body *PrepareAddonDraftJSONRequestBody
}

type PrepareAddonDraftResponseObject interface {
	VisitPrepareAddonDraftResponse(ctx fiber.Ctx) error
}

type PrepareAddonDraft200JSONResponse AddonPrepareResult

func (response PrepareAddonDraft200JSONResponse) VisitPrepareAddonDraftResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListConversationsRequestObject struct {
	Params ListConversationsParams
}

type ListConversationsResponseObject interface {
	VisitListConversationsResponse(ctx fiber.Ctx) error
}

type ListConversations200JSONResponse []Conversation

func (response ListConversations200JSONResponse) VisitListConversationsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetConversationRequestObject struct {
	ConversationId string `json:"conversationId"`
}

type GetConversationResponseObject interface {
	VisitGetConversationResponse(ctx fiber.Ctx) error
}

type GetConversation200JSONResponse ConversationDetail

func (response GetConversation200JSONResponse) VisitGetConversationResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListDraftsRequestObject struct {
}

type ListDraftsResponseObject interface {
	VisitListDraftsResponse(ctx fiber.Ctx) error
}

type ListDrafts200JSONResponse []Draft

func (response ListDrafts200JSONResponse) VisitListDraftsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type SaveDraftRequestObject struct {
	Body *SaveDraftJSONRequestBody
}

type SaveDraftResponseObject interface {
	VisitSaveDraftResponse(ctx fiber.Ctx) error
}

type SaveDraft200JSONResponse Draft

func (response SaveDraft200JSONResponse) VisitSaveDraftResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type DeleteDraftRequestObject struct {
	DraftId string `json:"draftId"`
}

type DeleteDraftResponseObject interface {
	VisitDeleteDraftResponse(ctx fiber.Ctx) error
}

type DeleteDraft204Response struct {
}

func (response DeleteDraft204Response) VisitDeleteDraftResponse(ctx fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type GetDraftRequestObject struct {
	DraftId string `json:"draftId"`
}

type GetDraftResponseObject interface {
	VisitGetDraftResponse(ctx fiber.Ctx) error
}

type GetDraft200JSONResponse Draft

func (response GetDraft200JSONResponse) VisitGetDraftResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(ctx fiber.Ctx) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListMailboxesRequestObject struct {
}

type ListMailboxesResponseObject interface {
	VisitListMailboxesResponse(ctx fiber.Ctx) error
}

type ListMailboxes200JSONResponse []Mailbox

func (response ListMailboxes200JSONResponse) VisitListMailboxesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type StartMailboxConnectRequestObject struct {
}

type StartMailboxConnectResponseObject interface {
	VisitStartMailboxConnectResponse(ctx fiber.Ctx) error
}

type StartMailboxConnect200JSONResponse ConnectURL

func (response StartMailboxConnect200JSONResponse) VisitStartMailboxConnectResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type RemoveMailboxRequestObject struct {
	MailboxId string `json:"mailboxId"`
}

type RemoveMailboxResponseObject interface {
	VisitRemoveMailboxResponse(ctx fiber.Ctx) error
}

type RemoveMailbox204Response struct {
}

func (response RemoveMailbox204Response) VisitRemoveMailboxResponse(ctx fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

type CreatePairingCodeRequestObject struct {
	Body *CreatePairingCodeJSONRequestBody
}

type CreatePairingCodeResponseObject interface {
	VisitCreatePairingCodeResponse(ctx fiber.Ctx) error
}

type CreatePairingCode200JSONResponse PairingCode

func (response CreatePairingCode200JSONResponse) VisitCreatePairingCodeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type SendTrackedMessageRequestObject struct {
	Body *SendTrackedMessageJSONRequestBody
}

type SendTrackedMessageResponseObject interface {
	VisitSendTrackedMessageResponse(ctx fiber.Ctx) error
}

type SendTrackedMessage200JSONResponse SendResult

func (response SendTrackedMessage200JSONResponse) VisitSendTrackedMessageResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /addon/pair)
	PairAddon(ctx context.Context, request PairAddonRequestObject) (PairAddonResponseObject, error)

	// (POST /addon/prepare)
	PrepareAddonDraft(ctx context.Context, request PrepareAddonDraftRequestObject) (PrepareAddonDraftResponseObject, error)

	// (GET /conversations)
	ListConversations(ctx context.Context, request ListConversationsRequestObject) (ListConversationsResponseObject, error)

	// (GET /conversations/{conversationId})
	GetConversation(ctx context.Context, request GetConversationRequestObject) (GetConversationResponseObject, error)

	// (GET /drafts)
	ListDrafts(ctx context.Context, request ListDraftsRequestObject) (ListDraftsResponseObject, error)

	// (POST /drafts)
	SaveDraft(ctx context.Context, request SaveDraftRequestObject) (SaveDraftResponseObject, error)

	// (DELETE /drafts/{draftId})
	DeleteDraft(ctx context.Context, request DeleteDraftRequestObject) (DeleteDraftResponseObject, error)

	// (GET /drafts/{draftId})
	GetDraft(ctx context.Context, request GetDraftRequestObject) (GetDraftResponseObject, error)

	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)

	// (GET /mailboxes)
	ListMailboxes(ctx context.Context, request ListMailboxesRequestObject) (ListMailboxesResponseObject, error)

	// (POST /mailboxes/connect)
	StartMailboxConnect(ctx context.Context, request StartMailboxConnectRequestObject) (StartMailboxConnectResponseObject, error)

	// (DELETE /mailboxes/{mailboxId})
	RemoveMailbox(ctx context.Context, request RemoveMailboxRequestObject) (RemoveMailboxResponseObject, error)

	// (POST /pairing-codes)
	CreatePairingCode(ctx context.Context, request CreatePairingCodeRequestObject) (CreatePairingCodeResponseObject, error)

	// (POST /send)
	SendTrackedMessage(ctx context.Context, request SendTrackedMessageRequestObject) (SendTrackedMessageResponseObject, error)
}

type StrictHandlerFunc func(ctx fiber.Ctx, args any) (any, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PairAddon operation middleware
func (sh *strictHandler) PairAddon(ctx fiber.Ctx) error {
	var request PairAddonRequestObject

	var body PairAddonJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PairAddon(ctx.Context(), request.(PairAddonRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PairAddon")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PairAddonResponseObject); ok {
		if err := validResponse.VisitPairAddonResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PrepareAddonDraft operation middleware
func (sh *strictHandler) PrepareAddonDraft(ctx fiber.Ctx) error {
	var request PrepareAddonDraftRequestObject

	var body PrepareAddonDraftJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PrepareAddonDraft(ctx.Context(), request.(PrepareAddonDraftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PrepareAddonDraft")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PrepareAddonDraftResponseObject); ok {
		if err := validResponse.VisitPrepareAddonDraftResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListConversations operation middleware
func (sh *strictHandler) ListConversations(ctx fiber.Ctx, params ListConversationsParams) error {
	var request ListConversationsRequestObject

	request.Params = params

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListConversations(ctx.Context(), request.(ListConversationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListConversations")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListConversationsResponseObject); ok {
		if err := validResponse.VisitListConversationsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetConversation operation middleware
func (sh *strictHandler) GetConversation(ctx fiber.Ctx, conversationId string) error {
	var request GetConversationRequestObject

	request.ConversationId = conversationId

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetConversation(ctx.Context(), request.(GetConversationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConversation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetConversationResponseObject); ok {
		if err := validResponse.VisitGetConversationResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListDrafts operation middleware
func (sh *strictHandler) ListDrafts(ctx fiber.Ctx) error {
	var request ListDraftsRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListDrafts(ctx.Context(), request.(ListDraftsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDrafts")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListDraftsResponseObject); ok {
		if err := validResponse.VisitListDraftsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SaveDraft operation middleware
func (sh *strictHandler) SaveDraft(ctx fiber.Ctx) error {
	var request SaveDraftRequestObject

	var body SaveDraftJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.SaveDraft(ctx.Context(), request.(SaveDraftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SaveDraft")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SaveDraftResponseObject); ok {
		if err := validResponse.VisitSaveDraftResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteDraft operation middleware
func (sh *strictHandler) DeleteDraft(ctx fiber.Ctx, draftId string) error {
	var request DeleteDraftRequestObject

	request.DraftId = draftId

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDraft(ctx.Context(), request.(DeleteDraftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDraft")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteDraftResponseObject); ok {
		if err := validResponse.VisitDeleteDraftResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetDraft operation middleware
func (sh *strictHandler) GetDraft(ctx fiber.Ctx, draftId string) error {
	var request GetDraftRequestObject

	request.DraftId = draftId

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetDraft(ctx.Context(), request.(GetDraftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDraft")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetDraftResponseObject); ok {
		if err := validResponse.VisitGetDraftResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx fiber.Ctx) error {
	var request GetHealthRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.Context(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListMailboxes operation middleware
func (sh *strictHandler) ListMailboxes(ctx fiber.Ctx) error {
	var request ListMailboxesRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListMailboxes(ctx.Context(), request.(ListMailboxesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMailboxes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListMailboxesResponseObject); ok {
		if err := validResponse.VisitListMailboxesResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// StartMailboxConnect operation middleware
func (sh *strictHandler) StartMailboxConnect(ctx fiber.Ctx) error {
	var request StartMailboxConnectRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.StartMailboxConnect(ctx.Context(), request.(StartMailboxConnectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartMailboxConnect")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(StartMailboxConnectResponseObject); ok {
		if err := validResponse.VisitStartMailboxConnectResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RemoveMailbox operation middleware
func (sh *strictHandler) RemoveMailbox(ctx fiber.Ctx, mailboxId string) error {
	var request RemoveMailboxRequestObject

	request.MailboxId = mailboxId

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveMailbox(ctx.Context(), request.(RemoveMailboxRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveMailbox")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RemoveMailboxResponseObject); ok {
		if err := validResponse.VisitRemoveMailboxResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreatePairingCode operation middleware
func (sh *strictHandler) CreatePairingCode(ctx fiber.Ctx) error {
	var request CreatePairingCodeRequestObject

	var body CreatePairingCodeJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePairingCode(ctx.Context(), request.(CreatePairingCodeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePairingCode")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreatePairingCodeResponseObject); ok {
		if err := validResponse.VisitCreatePairingCodeResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SendTrackedMessage operation middleware
func (sh *strictHandler) SendTrackedMessage(ctx fiber.Ctx) error {
	var request SendTrackedMessageRequestObject

	var body SendTrackedMessageJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.SendTrackedMessage(ctx.Context(), request.(SendTrackedMessageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SendTrackedMessage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SendTrackedMessageResponseObject); ok {
		if err := validResponse.VisitSendTrackedMessageResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
