// Package tracking provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package tracking

import (
	"context"
	"fmt"
	"net/url"
	"time"

	"github.com/gofiber/fiber/v3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ConversationOpenStatus.
const (
	ConversationOpenStatusNoOpenDetected ConversationOpenStatus = "no_open_detected"
	ConversationOpenStatusOpenDetected   ConversationOpenStatus = "open_detected"
)

// Valid indicates whether the value is a known member of the ConversationOpenStatus enum.
func (e ConversationOpenStatus) Valid() bool {
	switch e {
	case ConversationOpenStatusNoOpenDetected:
		return true
	case ConversationOpenStatusOpenDetected:
		return true
	default:
		return false
	}
}

// Defines values for ConversationDetailOpenStatus.
const (
	ConversationDetailOpenStatusNoOpenDetected ConversationDetailOpenStatus = "no_open_detected"
	ConversationDetailOpenStatusOpenDetected   ConversationDetailOpenStatus = "open_detected"
)

// Valid indicates whether the value is a known member of the ConversationDetailOpenStatus enum.
func (e ConversationDetailOpenStatus) Valid() bool {
	switch e {
	case ConversationDetailOpenStatusNoOpenDetected:
		return true
	case ConversationDetailOpenStatusOpenDetected:
		return true
	default:
		return false
	}
}

// Defines values for DeliveryStatus.
const (
	Failed   DeliveryStatus = "failed"
	Pending  DeliveryStatus = "pending"
	Prepared DeliveryStatus = "prepared"
	Sent     DeliveryStatus = "sent"
	Unknown  DeliveryStatus = "unknown"
)

// Valid indicates whether the value is a known member of the DeliveryStatus enum.
func (e DeliveryStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Pending:
		return true
	case Prepared:
		return true
	case Sent:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// AddonPairInput defines model for AddonPairInput.
type AddonPairInput struct {
	Code          string `json:"code"`
	IdentityToken string `json:"identityToken"`
}

// AddonPairResult defines model for AddonPairResult.
type AddonPairResult struct {
	MailboxId string `json:"mailboxId"`
}

// AddonPrepareInput defines model for AddonPrepareInput.
type AddonPrepareInput struct {
	IdentityToken string   `json:"identityToken"`
	Recipients    []string `json:"recipients"`
	Subject       string   `json:"subject"`
}

// AddonPrepareResult defines model for AddonPrepareResult.
type AddonPrepareResult struct {
	ConversationId string `json:"conversationId"`
	PixelUrl       string `json:"pixelUrl"`
}

// Conversation defines model for Conversation.
type Conversation struct {
	Id         string                 `json:"id"`
	MailboxId  string                 `json:"mailboxId"`
	OpenStatus ConversationOpenStatus `json:"openStatus"`
	Status     string                 `json:"status"`
	Subject    string                 `json:"subject"`
	UpdatedAt  time.Time              `json:"updatedAt"`
}

// ConversationOpenStatus defines model for Conversation.OpenStatus.
type ConversationOpenStatus string

// ConversationDetail defines model for ConversationDetail.
type ConversationDetail struct {
	Deliveries []Delivery                   `json:"deliveries"`
	Events     []OpenEvent                  `json:"events"`
	Id         string                       `json:"id"`
	MailboxId  string                       `json:"mailboxId"`
	OpenStatus ConversationDetailOpenStatus `json:"openStatus"`
	Status     string                       `json:"status"`
	Subject    string                       `json:"subject"`
	UpdatedAt  time.Time                    `json:"updatedAt"`
}

// ConversationDetailOpenStatus defines model for ConversationDetail.OpenStatus.
type ConversationDetailOpenStatus string

// Delivery defines model for Delivery.
type Delivery struct {
	Error              *string        `json:"error,omitempty"`
	GmailMessageId     *string        `json:"gmailMessageId,omitempty"`
	GmailThreadId      *string        `json:"gmailThreadId,omitempty"`
	Id                 string         `json:"id"`
	Recipients         []string       `json:"recipients"`
	ReplyAllRecipients []string       `json:"replyAllRecipients"`
	RfcMessageId       *string        `json:"rfcMessageId,omitempty"`
	Status             DeliveryStatus `json:"status"`
}

// DeliveryStatus defines model for Delivery.Status.
type DeliveryStatus string

// OpenEvent defines model for OpenEvent.
type OpenEvent struct {
	At         time.Time `json:"at"`
	DeliveryId string    `json:"deliveryId"`
}

// PairingCode defines model for PairingCode.
type PairingCode struct {
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expiresAt"`
}

// PairingCodeInput defines model for PairingCodeInput.
type PairingCodeInput struct {
	MailboxId string `json:"mailboxId"`
}

// ListConversationsParams defines parameters for ListConversations.
type ListConversationsParams struct {
	MailboxId *string `form:"mailboxId,omitempty" json:"mailboxId,omitempty"`
}

// PairAddonJSONRequestBody defines body for PairAddon for application/json ContentType.
type PairAddonJSONRequestBody = AddonPairInput

// PrepareAddonDraftJSONRequestBody defines body for PrepareAddonDraft for application/json ContentType.
type PrepareAddonDraftJSONRequestBody = AddonPrepareInput

// CreatePairingCodeJSONRequestBody defines body for CreatePairingCode for application/json ContentType.
type CreatePairingCodeJSONRequestBody = PairingCodeInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /addon/pair)
	PairAddon(c fiber.Ctx) error

	// (POST /addon/prepare)
	PrepareAddonDraft(c fiber.Ctx) error

	// (GET /conversations)
	ListConversations(c fiber.Ctx, params ListConversationsParams) error

	// (GET /conversations/{conversationId})
	GetConversation(c fiber.Ctx, conversationId string) error

	// (POST /pairing-codes)
	CreatePairingCode(c fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c fiber.Ctx, next fiber.Handler) error

// PairAddon operation middleware
func (siw *ServerInterfaceWrapper) PairAddon(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.PairAddon(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// PrepareAddonDraft operation middleware
func (siw *ServerInterfaceWrapper) PrepareAddonDraft(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.PrepareAddonDraft(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// ListConversations operation middleware
func (siw *ServerInterfaceWrapper) ListConversations(c fiber.Ctx) error {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListConversationsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "mailboxId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "mailboxId", query, &params.MailboxId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter mailboxId: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.ListConversations(c, params)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// GetConversation operation middleware
func (siw *ServerInterfaceWrapper) GetConversation(c fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "conversationId" -------------
	var conversationId string

	err = runtime.BindStyledParameterWithOptions("simple", "conversationId", c.Params("conversationId"), &conversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter conversationId: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.GetConversation(c, conversationId)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// CreatePairingCode operation middleware
func (siw *ServerInterfaceWrapper) CreatePairingCode(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.CreatePairingCode(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/conversations", wrapper.ListConversations)

	router.Get(options.BaseURL+"/conversations/:conversationId", wrapper.GetConversation)

	router.Post(options.BaseURL+"/pairing-codes", wrapper.CreatePairingCode)

	router.Post(options.BaseURL+"/addon/pair", wrapper.PairAddon)

	router.Post(options.BaseURL+"/addon/prepare", wrapper.PrepareAddonDraft)

}

type PairAddonRequestObject struct {
	Body *PairAddonJSONRequestBody
}

type PairAddonResponseObject interface {
	VisitPairAddonResponse(ctx fiber.Ctx) error
}

type PairAddon200JSONResponse AddonPairResult

func (response PairAddon200JSONResponse) VisitPairAddonResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type PrepareAddonDraftRequestObject struct {
	Body *PrepareAddonDraftJSONRequestBody
}

type PrepareAddonDraftResponseObject interface {
	VisitPrepareAddonDraftResponse(ctx fiber.Ctx) error
}

type PrepareAddonDraft200JSONResponse AddonPrepareResult

func (response PrepareAddonDraft200JSONResponse) VisitPrepareAddonDraftResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type ListConversationsRequestObject struct {
	Params ListConversationsParams
}

type ListConversationsResponseObject interface {
	VisitListConversationsResponse(ctx fiber.Ctx) error
}

type ListConversations200JSONResponse []Conversation

func (response ListConversations200JSONResponse) VisitListConversationsResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type GetConversationRequestObject struct {
	ConversationId string `json:"conversationId"`
}

type GetConversationResponseObject interface {
	VisitGetConversationResponse(ctx fiber.Ctx) error
}

type GetConversation200JSONResponse ConversationDetail

func (response GetConversation200JSONResponse) VisitGetConversationResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type CreatePairingCodeRequestObject struct {
	Body *CreatePairingCodeJSONRequestBody
}

type CreatePairingCodeResponseObject interface {
	VisitCreatePairingCodeResponse(ctx fiber.Ctx) error
}

type CreatePairingCode200JSONResponse PairingCode

func (response CreatePairingCode200JSONResponse) VisitCreatePairingCodeResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /addon/pair)
	PairAddon(ctx context.Context, request PairAddonRequestObject) (PairAddonResponseObject, error)

	// (POST /addon/prepare)
	PrepareAddonDraft(ctx context.Context, request PrepareAddonDraftRequestObject) (PrepareAddonDraftResponseObject, error)

	// (GET /conversations)
	ListConversations(ctx context.Context, request ListConversationsRequestObject) (ListConversationsResponseObject, error)

	// (GET /conversations/{conversationId})
	GetConversation(ctx context.Context, request GetConversationRequestObject) (GetConversationResponseObject, error)

	// (POST /pairing-codes)
	CreatePairingCode(ctx context.Context, request CreatePairingCodeRequestObject) (CreatePairingCodeResponseObject, error)
}

type StrictHandlerFunc func(ctx fiber.Ctx, args any) (any, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// PairAddon operation middleware
func (sh *strictHandler) PairAddon(ctx fiber.Ctx) error {
	var request PairAddonRequestObject

	var body PairAddonJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PairAddon(ctx.Context(), request.(PairAddonRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PairAddon")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PairAddonResponseObject); ok {
		if err := validResponse.VisitPairAddonResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// PrepareAddonDraft operation middleware
func (sh *strictHandler) PrepareAddonDraft(ctx fiber.Ctx) error {
	var request PrepareAddonDraftRequestObject

	var body PrepareAddonDraftJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.PrepareAddonDraft(ctx.Context(), request.(PrepareAddonDraftRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PrepareAddonDraft")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(PrepareAddonDraftResponseObject); ok {
		if err := validResponse.VisitPrepareAddonDraftResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListConversations operation middleware
func (sh *strictHandler) ListConversations(ctx fiber.Ctx, params ListConversationsParams) error {
	var request ListConversationsRequestObject

	request.Params = params

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListConversations(ctx.Context(), request.(ListConversationsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListConversations")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListConversationsResponseObject); ok {
		if err := validResponse.VisitListConversationsResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetConversation operation middleware
func (sh *strictHandler) GetConversation(ctx fiber.Ctx, conversationId string) error {
	var request GetConversationRequestObject

	request.ConversationId = conversationId

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.GetConversation(ctx.Context(), request.(GetConversationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConversation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetConversationResponseObject); ok {
		if err := validResponse.VisitGetConversationResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreatePairingCode operation middleware
func (sh *strictHandler) CreatePairingCode(ctx fiber.Ctx) error {
	var request CreatePairingCodeRequestObject

	var body CreatePairingCodeJSONRequestBody
	if err := ctx.Bind().Body(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePairingCode(ctx.Context(), request.(CreatePairingCodeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePairingCode")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreatePairingCodeResponseObject); ok {
		if err := validResponse.VisitCreatePairingCodeResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
