// Package mailboxes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package mailboxes

import (
	"context"
	"fmt"
	"time"

	"github.com/gofiber/fiber/v3"
	"github.com/oapi-codegen/runtime"
)

// ConnectURL defines model for ConnectURL.
type ConnectURL struct {
	Url string `json:"url"`
}

// Mailbox defines model for Mailbox.
type Mailbox struct {
	ConnectedAt time.Time `json:"connectedAt"`
	Email       string    `json:"email"`
	Id          string    `json:"id"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /mailboxes)
	ListMailboxes(c fiber.Ctx) error

	// (POST /mailboxes/connect)
	StartMailboxConnect(c fiber.Ctx) error

	// (DELETE /mailboxes/{mailboxId})
	RemoveMailbox(c fiber.Ctx, mailboxId string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []HandlerMiddlewareFunc
}

type MiddlewareFunc fiber.Handler
type HandlerMiddlewareFunc func(c fiber.Ctx, next fiber.Handler) error

// ListMailboxes operation middleware
func (siw *ServerInterfaceWrapper) ListMailboxes(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.ListMailboxes(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// StartMailboxConnect operation middleware
func (siw *ServerInterfaceWrapper) StartMailboxConnect(c fiber.Ctx) error {

	handler := func(c fiber.Ctx) error {
		return siw.Handler.StartMailboxConnect(c)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// RemoveMailbox operation middleware
func (siw *ServerInterfaceWrapper) RemoveMailbox(c fiber.Ctx) error {

	var err error
	_ = err

	// ------------- Path parameter "mailboxId" -------------
	var mailboxId string

	err = runtime.BindStyledParameterWithOptions("simple", "mailboxId", c.Params("mailboxId"), &mailboxId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter mailboxId: %w", err).Error())
	}

	handler := func(c fiber.Ctx) error {
		return siw.Handler.RemoveMailbox(c, mailboxId)
	}

	for i := len(siw.HandlerMiddlewares) - 1; i >= 0; i-- {
		m := siw.HandlerMiddlewares[i]
		next := handler
		handler = func(c fiber.Ctx) error {
			return m(c, next)
		}
	}

	return handler(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL            string
	Middlewares        []MiddlewareFunc
	HandlerMiddlewares []HandlerMiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.HandlerMiddlewares,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/mailboxes", wrapper.ListMailboxes)

	router.Post(options.BaseURL+"/mailboxes/connect", wrapper.StartMailboxConnect)

	router.Delete(options.BaseURL+"/mailboxes/:mailboxId", wrapper.RemoveMailbox)

}

type ListMailboxesRequestObject struct {
}

type ListMailboxesResponseObject interface {
	VisitListMailboxesResponse(ctx fiber.Ctx) error
}

type ListMailboxes200JSONResponse []Mailbox

func (response ListMailboxes200JSONResponse) VisitListMailboxesResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type StartMailboxConnectRequestObject struct {
}

type StartMailboxConnectResponseObject interface {
	VisitStartMailboxConnectResponse(ctx fiber.Ctx) error
}

type StartMailboxConnect200JSONResponse ConnectURL

func (response StartMailboxConnect200JSONResponse) VisitStartMailboxConnectResponse(ctx fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(200)

	return ctx.JSON(&response)
}

type RemoveMailboxRequestObject struct {
	MailboxId string `json:"mailboxId"`
}

type RemoveMailboxResponseObject interface {
	VisitRemoveMailboxResponse(ctx fiber.Ctx) error
}

type RemoveMailbox204Response struct {
}

func (response RemoveMailbox204Response) VisitRemoveMailboxResponse(ctx fiber.Ctx) error {
	ctx.Status(204)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /mailboxes)
	ListMailboxes(ctx context.Context, request ListMailboxesRequestObject) (ListMailboxesResponseObject, error)

	// (POST /mailboxes/connect)
	StartMailboxConnect(ctx context.Context, request StartMailboxConnectRequestObject) (StartMailboxConnectResponseObject, error)

	// (DELETE /mailboxes/{mailboxId})
	RemoveMailbox(ctx context.Context, request RemoveMailboxRequestObject) (RemoveMailboxResponseObject, error)
}

type StrictHandlerFunc func(ctx fiber.Ctx, args any) (any, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListMailboxes operation middleware
func (sh *strictHandler) ListMailboxes(ctx fiber.Ctx) error {
	var request ListMailboxesRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ListMailboxes(ctx.Context(), request.(ListMailboxesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListMailboxes")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListMailboxesResponseObject); ok {
		if err := validResponse.VisitListMailboxesResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// StartMailboxConnect operation middleware
func (sh *strictHandler) StartMailboxConnect(ctx fiber.Ctx) error {
	var request StartMailboxConnectRequestObject

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.StartMailboxConnect(ctx.Context(), request.(StartMailboxConnectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartMailboxConnect")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(StartMailboxConnectResponseObject); ok {
		if err := validResponse.VisitStartMailboxConnectResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RemoveMailbox operation middleware
func (sh *strictHandler) RemoveMailbox(ctx fiber.Ctx, mailboxId string) error {
	var request RemoveMailboxRequestObject

	request.MailboxId = mailboxId

	handler := func(ctx fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveMailbox(ctx.Context(), request.(RemoveMailboxRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveMailbox")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RemoveMailboxResponseObject); ok {
		if err := validResponse.VisitRemoveMailboxResponse(ctx); err != nil {
			return err
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
